---
title: "Coxph Report nAb"
author: "CoVPN 3008"
date: "2024-10-30"
output: pdf_document
---

```{r setup, include=FALSE}
# Change the directory as needed
setwd('Github/antibody_manuscript/Cox_HR_nAb/')
set.seed(1)
knitr::opts_chunk$set(echo = TRUE)
```

## Preparing the dataset

```{r load pckages, echo=FALSE, warning=FALSE, message=FALSE}
library(CaseCohortCoxSurvival)
library(survival)
library(dplyr)
library(survey)
library(ggplot2)
library(GGally)
library(vaccine)
library(wCorr)
library(haven)
library(Hmisc)
library(coxphw)
source('coxph_functions_serum.R')
```

# Data preprocessing

```{r data wrangling, echo=FALSE}
# Read in the processed dataset
dt = read.csv('./COVID_realdata_ics_bama_nab_bcp20241210_processed_with_riskscore.csv')

# Additional data processing
# Define log10-transformed marker variables
# If a participant is not in the phase-2 sample, then set the 
# participant's immune marker to NA
dt_serum_PP = dt %>%
  filter(ph1.m1.sera == 1) %>%
  mutate(hybrid = AGRP2N %in% c(2.1, 4.1) + 0) %>%
  mutate(is.subcohort = ifelse(IMMFL == 'Y', 1, 0)) %>%
  mutate(log10M1BA45ID50 = log10(M1BA45ID50),
         log10BBA45ID50 = log10(BBA45ID50),
         frBA45ID50 = log10M1BA45ID50 - log10BBA45ID50,
         log10M1IGGSpikeIndex = log10(M1IGGMSDA16AU), #A16 = IgG S Index
         log10BIGGSpikeIndex = log10(BIGGMSDA16AU), 
         frIGGSpikeIndex = log10M1IGGSpikeIndex - log10BIGGSpikeIndex,
         log10M1IGGSpikeBA45 = log10(M1IGGMSDA23AU), # A23 = IgG S BA.4/5
         log10BIGGSpikeBA45 = log10(BIGGMSDA23AU), 
         frIGGSpikeBA45 = log10M1IGGSpikeBA45 - log10BIGGSpikeBA45,
         log10M1IGGN = log10(M1IGGMSDA15AU),
         log10BIGGN = log10(BIGGMSDA15AU)) %>%
  mutate(log10M1BA45ID50 = ifelse(ph2.m1.sera == 1, log10M1BA45ID50, NA),
         log10BBA45ID50 = ifelse(ph2.m1.sera == 1, log10BBA45ID50, NA),
         frBA45ID50 = ifelse(ph2.m1.sera == 1, frBA45ID50, NA),
         log10M1IGGSpikeIndex = ifelse(ph2.m1.sera == 1, log10M1IGGSpikeIndex, NA),
         log10BIGGSpikeIndex = ifelse(ph2.m1.sera == 1, log10BIGGSpikeIndex, NA),
         frIGGSpikeIndex = ifelse(ph2.m1.sera == 1, frIGGSpikeIndex, NA),
         log10M1IGGSpikeBA45 = ifelse(ph2.m1.sera == 1, log10M1IGGSpikeBA45, NA),
         log10BIGGSpikeBA45 = ifelse(ph2.m1.sera == 1, log10BIGGSpikeBA45, NA),
         frIGGSpikeBA45 = ifelse(ph2.m1.sera == 1, frIGGSpikeBA45, NA),
         log10M1IGGN = ifelse(ph2.m1.sera == 1, log10M1IGGN, NA),
         log10BIGGN = ifelse(ph2.m1.sera == 1, log10BIGGN, NA))

# Define a stratification variable W corresponding to
# 4 baseline strata + case
# Mutate ph2 to logical 
dt_serum_PP = dt_serum_PP %>%
  mutate(W = ifelse(EventIndPrimary1 == 1, 1, 
                    ifelse(AGRP2N == 1, 2, 
                           ifelse(AGRP2N == 2.1, 3,
                                  ifelse(AGRP2N == 3, 4, 5))))) %>%
  mutate(ph2.m1.sera_logical = ifelse(ph2.m1.sera == 1, TRUE, FALSE))

# Additional data processing
# Derive baseline variables to be adjusted for in the 
# antibody immune correlates analysis
dt_serum_PP = dt_serum_PP %>%
  mutate(TBFL = ifelse(TBFL == '', 'N', TBFL),
         TBFL = ifelse(TBFL == 'Y', 1, 0)) %>%
  mutate(AGEGR1 = ifelse(AGEGR1 == '>40', 1, 0),
         BMIB2GR1 = ifelse(BMIB2GR1 == '>25', 1, 0),
         CD4B2GR1 = ifelse(is.na(CD4B2GR1), 'NotKnown', 
                           ifelse(CD4B2GR1 == '<=500', 'low', 'high')),
         riskscore = ifelse(is.na(riskscore), median(riskscore, na.rm = T), riskscore),
         enrollmentPeriodEarly = ifelse(CalendarDateEnrollment <= 90, 1, 0),
         enrollmentPeriodMid = ifelse((CalendarDateEnrollment > 90 & CalendarDateEnrollment <= 180), 1, 0),
         regionRSA = ifelse(REGION == 'South Africa', 1, 0))

# Analysis in this file focuses on PLWH
dt_serum_PP = dt_serum_PP %>%
  filter(AGRP2N %in% c(1, 2.1))
```

## Define serum markers

```{r setmarkerofinterest, echo=TRUE}
antigen_vec = c('BA45ID50', 'IGGSpikeIndex', 'IGGSpikeBA45', 'IGGN')
antigen_names_vec = c('nAb ID50 BA.4/5', 'IgG S Index',  
                      'IgG S BA.4/5', 'IgG N Index')
mk_vec_b = paste0('log10B', antigen_vec)
names_vec_b = c('M0 nAb-ID50 BA.4/5 (AU/ml)',
              'M0 IgG S Index (AU/ml)',
              'M0 IgG S BA.4/5 (AU/ml)',
              'M0 IgG N Index (AU/ml)')

mk_vec_p = paste0('log10M1', antigen_vec)
names_vec_p = c('M1 nAb-ID50 BA.4/5 (AU/ml)',
              'M1 IgG S Index (AU/ml)',
              'M1 IgG S BA.4/5 (AU/ml)',
              'M1 IgG N Index (AU/ml)')

mk_vec_fr = c('frBA45ID50', 'frIGGSpikeIndex', 'frIGGSpikeBA45')
names_vec_fr = c('Fold-rise nAb-ID50 BA.4/5 (AU/ml)',
              'Fold-rise IgG S Index (AU/ml)',
              'Fold-rise IgG S BA.4/5 (AU/ml)')
```

## Define adjusted covariates. 

```{r adj covs}
# No HIV because we focus on PLWH
adj_vars = c('regionRSA', 'TBFL', 'riskscore', 
             'enrollmentPeriodEarly', 'enrollmentPeriodMid') 
n_var = 5
```

# Hybrid immunity group correlates of risk analysis

```{r cohort HIPP}
dt_serum_PP_HIPP = dt_serum_PP %>%
  filter(hybrid == 1)
```

## Univariate Correlates of Risk Analysis

```{r univaraite CoR HIPP, echo = TRUE, warning=FALSE, message=FALSE}
# Analysis conducted for each M0, Peak, and Fold-rise marker
mk_vec = c(mk_vec_b, mk_vec_p, mk_vec_fr)
names_vec = c(names_vec_b, names_vec_p, names_vec_fr)
res = NULL
for (mk in mk_vec){
  md <- case_cohort_Cox_1(data = dt_serum_PP_HIPP, caseInd = "EventIndPrimary1", 
                            subcohortInd = "is.subcohort", 
                            baseline_strata  = "AGRP2N", 
                            time_to_event = 'EventTimePrimary', 
                            phase1_var_list = adj_vars, 
                            phase2_var_list  = mk)
  coxfit = process_cccs_output(md)
  res = rbind(res, coxfit[nrow(coxfit),]) # Last row is the marker
}
res$term = names_vec
knitr::kable(res, digits = 3, row.names = FALSE, 
             col.names = c('Covariate', 'HR', 'P-Value', 'Lower CI', 'Upper CI'))
```

# Vaccine immunity correlates of risk analysis

```{r cohort VIPP}
dt_serum_PP_VIPP = dt_serum_PP %>%
  filter(hybrid == 0) %>%
  mutate(vaccine = 1)
```

## Univariate Correlates of Risk Analysis: peak markers

```{r univariate VIPP, echo = TRUE, warning=FALSE, message=FALSE}
res = NULL
for (mk in c(mk_vec_p)){
  md <- case_cohort_Cox_1(data = dt_serum_PP_VIPP, caseInd = "EventIndPrimary1", 
                            subcohortInd = "is.subcohort", 
                            baseline_strata  = "AGRP2N", 
                            time_to_event = 'EventTimePrimary', 
                            phase1_var_list = adj_vars, 
                            phase2_var_list  = mk)
  coxfit = process_cccs_output(md)
  res = rbind(res, coxfit[nrow(coxfit),]) # Last row is the marker
}
res$term = c(names_vec_p)
knitr::kable(res, digits = 3, row.names = FALSE, 
             col.names = c('Covariate', 'HR', 'P-Value', 'Lower CI', 'Upper CI'))
```
