---
title: "Coxph Report nAb"
author: "CoVPN 3008"
date: "2024-10-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Change the directory as needed
setwd('Github/antibody_manuscript/Cox_HR_nAb/')
set.seed(1)
setwd("C:/Users/bzhang3/Dropbox/3008 correlates/manuscript/antibody_manuscript/NAb_curves/")
```

```{r load pckages, echo=FALSE, warning=FALSE, message=FALSE}
library(CaseCohortCoxSurvival)
library(survival)
library(dplyr)
library(survey)
library(ggplot2)
library(GGally)
library(vaccine)
library(wCorr)
library(haven)
library(Hmisc)
source('CVE_functions.R')
```


# Data preprocessing

```{r data wrangling, echo=FALSE}
# Read in the processed dataset
dt = read.csv('./COVID_realdata_ics_bama_nab_bcp20241210_processed_with_riskscore.csv')

# Additional data processing
# Define log10-transformed marker variables
# If a participant is not in the phase-2 sample, then set the 
# participant's immune marker to NA
dt_serum_PP = dt %>%
  filter(ph1.m1.sera == 1) %>%
  mutate(hybrid = AGRP2N %in% c(2.1, 4.1) + 0) %>%
  mutate(is.subcohort = ifelse(IMMFL == 'Y', 1, 0)) %>%
  mutate(log10M1BA45ID50 = log10(M1BA45ID50),
         log10BBA45ID50 = log10(BBA45ID50),
         frBA45ID50 = log10M1BA45ID50 - log10BBA45ID50,
         log10M1IGGSpikeIndex = log10(M1IGGMSDA16AU), #A16 = IgG S Index
         log10BIGGSpikeIndex = log10(BIGGMSDA16AU), 
         frIGGSpikeIndex = log10M1IGGSpikeIndex - log10BIGGSpikeIndex,
         log10M1IGGSpikeBA45 = log10(M1IGGMSDA23AU), # A23 = IgG S BA.4/5
         log10BIGGSpikeBA45 = log10(BIGGMSDA23AU), 
         frIGGSpikeBA45 = log10M1IGGSpikeBA45 - log10BIGGSpikeBA45,
         log10M1IGGN = log10(M1IGGMSDA15AU),
         log10BIGGN = log10(BIGGMSDA15AU))

# Define a stratification variable W corresponding to
# 4 baseline strata + case
# Mutate ph2 to logical 
dt_serum_PP = dt_serum_PP %>%
  mutate(W = ifelse(EventIndPrimary1 == 1, 1, 
                    ifelse(AGRP2N == 1, 2, 
                           ifelse(AGRP2N == 2.1, 3,
                                  ifelse(AGRP2N == 3, 4, 5))))) %>%
  mutate(ph2.m1.sera_logical = ifelse(ph2.m1.sera == 1, TRUE, FALSE))

# Additional data processing
# Derive baseline variables to be adjusted for in the 
# antibody immune correlates analysis
dt_serum_PP = dt_serum_PP %>%
  mutate(TBFL = ifelse(TBFL == '', 'N', TBFL),
         TBFL = ifelse(TBFL == 'Y', 1, 0)) %>%
  mutate(AGEGR1 = ifelse(AGEGR1 == '>40', 1, 0),
         BMIB2GR1 = ifelse(BMIB2GR1 == '>25', 1, 0),
         CD4B2GR1 = ifelse(is.na(CD4B2GR1), 'NotKnown', 
                           ifelse(CD4B2GR1 == '<=500', 'low', 'high')),
         riskscore = ifelse(is.na(riskscore), median(riskscore, na.rm = T), riskscore),
         enrollmentPeriodEarly = ifelse(CalendarDateEnrollment <= 90, 1, 0),
         enrollmentPeriodMid = ifelse((CalendarDateEnrollment > 90 & CalendarDateEnrollment <= 180), 1, 0),
         regionRSA = ifelse(REGION == 'South Africa', 1, 0))
```

# Define a 3-month endpoint: EventIndPrimary2 and EventTimePrimary2

Among 220 endpoints, 35 (20 Hybrid Group and 15 Vaccine Group) happened by 92 days post the Peak

```{r 3 month, echo=FALSE}
# 35 cases in the first 3 months
# 33 had serum samples avaiable, so case weight is 1.06
dt_serum_PP = dt_serum_PP %>%
  mutate(EventIndPrimary2 = ifelse(EventIndPrimary1 == 1 & EventTimePrimary <= 92, 1, 0)) %>%
  mutate(EventTimePrimary2 = pmin(EventTimePrimary, 92)) %>%
  mutate(wt.m1.sera = ifelse(EventIndPrimary2 == 1, 1.06, wt.m1.sera))
```


## Define serum markers
```{r setmarkerofinterest, echo=TRUE}
antigen_vec = c('BA45ID50', 'IGGSpikeIndex', 'IGGSpikeBA45', 'IGGN')
antigen_names_vec = c('nAb ID50 BA.4/5', 'IgG S Index',  
                      'IgG Spike BA.4/5', 'IgG N Index')
mk_vec_b = paste0('log10B', antigen_vec)
names_vec_b = c('M0 nAb-ID50 BA.4/5 (AU/ml)',
              'M0 IgG S Index (AU/ml)',
              'M0 IgG Spike BA.4/5 (AU/ml)',
              'M0 IgG N Index (AU/ml)')

mk_vec_p = paste0('log10M1', antigen_vec)
names_vec_p = c('Peak nAb-ID50 BA.4/5 (AU/ml)',
              'Peak IgG S Index (AU/ml)',
              'Peak IgG Spike BA.4/5 (AU/ml)',
              'Peak IgG N Index (AU/ml)')

mk_vec_fr = c('frBA45ID50', 'frIGGSpikeBA45')
names_vec_fr = c('Fold-rise nAb-ID50 BA.4/5 (AU/ml)',
              'Fold-rise IgG Spike BA.4/5 (AU/ml)')
```


## Define adjusted covariates
```{r adj covs}
adj_vars = c('riskscore') 
n_var = 1
```
# Vaccine immunity group controlled risk analysis 

```{r cohort VIPP}
dt_serum_PP_VIPP = dt_serum_PP %>%
  filter(hybrid == 0) %>%
  mutate(vaccine = 1)
```

## Plot the controlled risk curve for peak markers

```{r helper function plot, echo = FALSE}
plot_cr2 <- function(ests_cox, ests_np, mk_dist, overall_incidence,
                    xlab_name = 'log10 CD4+ IFNg OR IL-2 (%)',
                    title_name = 'Hybird Immunity Per-Protocol Group (HIPP)',
                    t0 = 165, x_range = c(-2, 1), y_range = c(0,0.02),
                    x_breaks = c(-2, -1, 0, 1),
                    x_labels = c('-2', '-1', '0', '1')){
  
  density = list(s = as.vector(unlist(mk_dist[,1])),
                 w = as.vector(unlist(mk_dist[,2])))
  low = quantile(density$s, c(0.025, 0.975))[1]
  high = quantile(density$s, c(0.025, 0.975))[2]
  
  Cox = truncate_ce(ests_cox, low, high)
  Nonparametric = truncate_ce(ests_np, low, high)
  
  p = plot_ce(Nonparametric,
              zoom_y = y_range, zoom_x = x_range) +
    geom_density(aes(x = x, y = y_range[2]*after_stat(scaled), weight = w), 
                 data = data.frame(x = density$s, w = density$w), 
                 inherit.aes = F, 
                 bounds = c(min(density$s), max(density$s)),
                 fill = "forestgreen", alpha = 0.3, color = NA) +
    geom_hline(yintercept = overall_incidence, 
               color = 'gray41', linetype = 'dashed') +
    scale_x_continuous(breaks = x_breaks, labels = x_labels) +
    scale_y_continuous(labels = function(x) paste0(x*100, "%")) +
    xlab(xlab_name) + 
    ylab(paste0('Covariate-adjusted risk \n', t0, ' days post M1')) +
    labs(title = title_name) +
    theme_bw(base_size = 18) + 
    theme(legend.position = 'bottom')
  
  print(p)
}

```

```{r controlled VE VIPP, echo=FALSE, message=FALSE, warning=FALSE}
controlled_ve_mk_vec = c(mk_vec_p)
controlled_ve_names_vec = c(names_vec_p)

a = length(controlled_ve_mk_vec)
for (i in 1:a){
  mk = controlled_ve_mk_vec[i]  
  cat(mk, '\n')
  dat <- load_data(
  time = 'EventTimePrimary',
  event = 'EventIndPrimary1',
  vacc = 'vaccine',
  marker = mk,
  covariates = adj_vars,
  weights = "wt.m1.sera",
  ph2 = "ph2.m1.sera",
  data = dt_serum_PP_VIPP)

b = vaccine::est_overall(dat, t_0 = 92, ve = FALSE)

overall_incidence = b$est[b$group == 'vaccine']  

ests_cox <- est_ce(dat = dat, type="Cox", t_0 = 92, return_p_value = TRUE, 
                   cve = FALSE)
ests_np <- est_ce(dat = dat, type="NP", t_0 = 92, return_p_value = TRUE, 
                  cve = FALSE)

df_np = data.frame(marker_level =  ests_np$cr$s,
                      controlled_risk =  ests_np$cr$est, 
                      ci_lower =  ests_np$cr$ci_lower, 
                      ci_upper =  ests_np$cr$ci_upper) 
write.csv(df_np, paste0( './source_data/Fig3_VIPP_',  mk, '_3month.csv'))

mk_dist = dt_serum_PP_VIPP %>%
  filter(ph2.m1.sera == 1) %>%
  select(!!sym(mk), wt.m1.sera)

p = plot_cr2(ests_cox, ests_np, mk_dist, overall_incidence,
                     xlab_name = controlled_ve_names_vec[i],
                     title_name = 'Marker-Specific Risk',
                     t0 = 92, x_range = c(-0.5, 7.5), y_range = c(0, 0.02),
                     x_breaks = seq(0, 7, 1),
                     x_labels =  c(expression(10^0), expression(10^1), expression(10^2),
                                   expression(10^3), expression(10^4), expression(10^5),
                                   expression(10^6), expression(10^7)))
p = p + geom_line(linewidth = 1.1) + 
  geom_ribbon(ggplot2::aes(ymin = ci_lower, ymax = ci_upper), 
              alpha = 0.2, linewidth = 1.1, linetype = "dotted") +
  theme_bw(base_size = 30) + 
  theme(legend.position = 'none') + ggtitle('')

saveRDS(p, paste0('./raw_data_for_figure/', controlled_ve_mk_vec[i], '_VIPP_3month.RData'))

ggsave(paste0('./Figure/', controlled_ve_mk_vec[i], '_VIPP_3month.pdf'),
       p, width = 12, height = 8, units = 'in')
}
```
