---
title: "Coxph Report ICS"
author: "CoVPN 3008"
date: "2024-10-31"
output: pdf_document
---

```{r setup, include=FALSE}
# Change the directory as needed
setwd('Github/Tcell_manuscript/Cox_HR_ICS/')
knitr::opts_chunk$set(echo = TRUE)
set.seed(1)
```


```{r load pckages, echo=FALSE, warning=FALSE, message=FALSE}
library(CaseCohortCoxSurvival)
library(survival)
library(dplyr)
library(survey)
library(ggplot2)
library(vaccine)
library(wCorr)
library(coxphw)
library(haven)
library(GGally)
source('coxph_functions_PBMC.R')
```

# Data preprocessing

```{r data wrangling, echo=FALSE}
# Read in the processed dataset
dt = read.csv('./COVID_realdata_ics_bama_nab_bcp20241210_processed_with_riskscore.csv')

# PBMC correlates analysis is restricted to PLWH (ph1.m1.ics = 1)
dt_PBMC_PP = dt %>% 
  filter(ph1.m1.ics == 1) %>%
  mutate(hybrid = (AGRP2N == 2.1) + 0) %>%
  mutate(is.subcohort = ifelse(ph2.m1.ics == 1 & IMMFL == 'Y', 1, 0))

# Define a stratification variable W corresponding to
# 4 baseline strata + case
# Mutate ph2 to logical 
dt_PBMC_PP = dt_PBMC_PP %>%
  mutate(W = ifelse(EventIndPrimary1 == 1, 1, 
                    ifelse(AGRP2N == 1, 2, 3))) %>%
  mutate(ph2.m1.ics_logical = ifelse(ph2.m1.ics == 1, TRUE, FALSE))

dt_PBMC_PP = dt_PBMC_PP %>%
  mutate(TBFL = ifelse(TBFL == '', 'N', TBFL),
         TBFL = ifelse(TBFL == 'Y', 1, 0)) %>%
  mutate(AGEGR1 = ifelse(AGEGR1 == '>40', 1, 0),
         BMIB2GR1 = ifelse(BMIB2GR1 == '>25', 1, 0),
         CD4B2GR1 = ifelse(is.na(CD4B2GR1), 'NotKnown', 
                           ifelse(CD4B2GR1 == '<=500', 'low', 'high')),
         riskscore = ifelse(is.na(riskscore), median(riskscore, na.rm = T), riskscore),
         enrollmentPeriodEarly = ifelse(CalendarDateEnrollment <= 90, 1, 0),
         enrollmentPeriodMid = ifelse((CalendarDateEnrollment > 90 & CalendarDateEnrollment <= 180), 1, 0),
         regionRSA = ifelse(REGION == 'South Africa', 1, 0))
```

## Define markers
```{r setmarkerofinterest, echo=TRUE}
# A11 = Spike BA.4/5; A02 = BA.4/5 N; A10 = Any BA.4/5
# C03: 'IFNg OR IL-2'; C04: 'IFNg OR IL-2 OR CD154'
T_vec = c('T4')
T_names_vec = c('CD4+')
C_vec = c('C03', 'C04')
C_names_vec = c('IFNg OR IL-2', 'IFNg OR IL-2 OR CD154')

A_vec = c('A02',  'A11')
A_names_vec = c('N BA.4/5', 'S BA.4/5')

antigen_vec = NULL
antigen_names_vec = NULL
for (i in 1:length(T_vec)) {
  for (j in 1:length(C_vec)) {
    for (k in 1:length(A_vec)) {
      antigen_vec = c(antigen_vec,
                      paste0(T_vec[i], C_vec[j], A_vec[k]))
      antigen_names_vec = c(antigen_names_vec,
                            paste0(T_names_vec[i], ' ', C_names_vec[j], '\n', A_names_vec[k]))
    }
  }
} 

mk_vec_b = paste0('B', antigen_vec)
names_vec_b = paste0('M0 ', antigen_names_vec, ' (%)')

mk_vec_p = paste0('M1', antigen_vec)
names_vec_p = paste0('M1 ', antigen_names_vec, ' (%)')


process <- function(x) log10(ifelse(x < 0.01, 0.01, x))

dt_PBMC_PP = dt_PBMC_PP %>%
  mutate_at(mk_vec_b, process) %>%
  mutate_at(mk_vec_p, process)

# Add fold-rise markers
for (antigen in antigen_vec) {
  dt_PBMC_PP = dt_PBMC_PP %>%
    mutate(!!paste0('fr', antigen) :=  !!sym(paste0('M1', antigen)) - !!sym(paste0('B', antigen)))
}

dt_PBMC_PP = dt_PBMC_PP %>%
  mutate(BT4C03A02 = ifelse(ph2.m1.ics == 1, BT4C03A02, NA),
         M1T4C03A02 = ifelse(ph2.m1.ics == 1, M1T4C03A02, NA),
         BT4C04A02 = ifelse(ph2.m1.ics == 1, BT4C04A02, NA),
         M1T4C04A02 = ifelse(ph2.m1.ics == 1, M1T4C04A02, NA),
         BT4C03A11 = ifelse(ph2.m1.ics == 1, BT4C03A11, NA),
         M1T4C03A11 = ifelse(ph2.m1.ics == 1, M1T4C03A11, NA),
         BT4C04A11 = ifelse(ph2.m1.ics == 1, BT4C04A11, NA),
         M1T4C04A11 = ifelse(ph2.m1.ics == 1, M1T4C04A11, NA))
```


## Define adjusted covariates
```{r adj covs}
adj_vars = c('riskscore') 
```


# Hybrid immunity group correlates of risk analysis

```{r cohort HIPP}
dt_PBMC_PP_HIPP = dt_PBMC_PP %>%
  filter(hybrid == 1)
```

## Univariate Correlates of Risk Analysis: baseline (M0) and approximate peak (M1) markers

```{r univariate HIPP, echo = TRUE, warning=FALSE, message=FALSE}
antigen_vec = NULL
antigen_names_vec = NULL
for (i in 1:length(T_vec)) {
  for (j in 1:length(C_vec)) {
    for (k in 1:length(A_vec)) {
      antigen_vec = c(antigen_vec,
                      paste0(T_vec[i], C_vec[j], A_vec[k]))
      antigen_names_vec = c(antigen_names_vec,
                            paste0(T_names_vec[i], ' ', C_names_vec[j], ' ', A_names_vec[k]))
    }
  }
} 

mk_vec_b = paste0('B', antigen_vec)
names_vec_b = paste0('M0 ', antigen_names_vec, ' (%)')

mk_vec_p = paste0('M1', antigen_vec)
names_vec_p = paste0('M1 ', antigen_names_vec, ' (%)')

res = NULL
for (mk in c(mk_vec_b, mk_vec_p) ){
  md <- case_cohort_Cox_1(data = dt_PBMC_PP_HIPP, caseInd = "EventIndPrimary1", 
                            subcohortInd = "is.subcohort", 
                            baseline_strata  = "AGRP2N", 
                            time_to_event = 'EventTimePrimary', 
                            phase1_var_list = adj_vars, 
                            phase2_var_list  = c(mk))
  coxfit = process_cccs_output_sd(md) # HR for a 3-fold increase
  res = rbind(res, coxfit[nrow(coxfit),]) # Last row is the marker
}

res$term = c(names_vec_b, names_vec_p)
knitr::kable(res, digits = 3, row.names = FALSE, 
             col.names = c('Covariate', 'HR', 'P-Value', 'Lower CI', 'Upper CI'))
```

## Univariate Correlates of Risk Analysis: interaction term

```{r interaction HIPP, echo = TRUE, warning=FALSE, message=FALSE}
antigen_vec = NULL
antigen_names_vec = NULL
for (i in 1:length(T_vec)) {
  for (j in 1:length(C_vec)) {
    for (k in 1:length(A_vec)) {
      antigen_vec = c(antigen_vec,
                      paste0(T_vec[i], C_vec[j], A_vec[k]))
      antigen_names_vec = c(antigen_names_vec,
                            paste0(T_names_vec[i], ' ', C_names_vec[j], ' ', A_names_vec[k]))
    }
  }
} 

mk_vec_b = paste0('B', antigen_vec)
names_vec_b = paste0('M0 ', antigen_names_vec, ' (%)')

mk_vec_p = paste0('M1', antigen_vec)
names_vec_p = paste0('M1 ', antigen_names_vec, ' (%)')

res = NULL
for (mk in c(mk_vec_b, mk_vec_p) ){
  dt_PBMC_PP_HIPP  = dt_PBMC_PP_HIPP %>%
    mutate(HIVBLN = ifelse(HIVBL == 'Positive', 1, 0)) %>%
    mutate(interaction_term = !!sym(mk) * HIVBLN)
  md <- case_cohort_Cox_1(data = dt_PBMC_PP_HIPP, caseInd = "EventIndPrimary1", 
                            subcohortInd = "is.subcohort", 
                            baseline_strata  = "AGRP2N", 
                            time_to_event = 'EventTimePrimary', 
                            phase1_var_list = adj_vars, 
                            phase2_var_list  = c(mk, 'interaction_term'))
  coxfit = process_cccs_output(md)
  res = rbind(res, coxfit[nrow(coxfit),]) # Last row is the marker
}

res$term = c(names_vec_b, names_vec_p)
knitr::kable(res, digits = 3, row.names = FALSE, 
             col.names = c('Covariate', 'HR', 'P-Value', 'Lower CI', 'Upper CI'))
```


## Univariate Correlates of Risk Analysis: fold-rise markers

```{r fold-rise HIPP, echo = TRUE, warning=FALSE, message=FALSE}
res = NULL
for (mk in paste0('fr', antigen_vec)){
  md <- case_cohort_Cox_1(data = dt_PBMC_PP_HIPP, caseInd = "EventIndPrimary1", 
                            subcohortInd = "is.subcohort", 
                            baseline_strata  = "AGRP2N", 
                            time_to_event = 'EventTimePrimary', 
                            phase1_var_list = adj_vars, 
                            phase2_var_list  = mk)
  coxfit = process_cccs_output_sd(md) 
  res = rbind(res, coxfit[nrow(coxfit),]) # Last row is the marker
}
res$term = paste0('Fold-rise ', antigen_names_vec)
knitr::kable(res, digits = 3, row.names = FALSE, 
             col.names = c('Covariate', 'HR', 'P-Value', 'Lower CI', 'Upper CI'))
```
