---
title: "Coxph Report ICS"
author: "CoVPN 3008"
date: "2024-10-13"
output: pdf_document
---

```{r setup, include=FALSE}
# Change the directory as needed
setwd('Github/Tcell_manuscript/ICS_curves/')
knitr::opts_chunk$set(echo = TRUE)
set.seed(1)
```

```{r load pckages, echo=FALSE, warning=FALSE, message=FALSE}
library(CaseCohortCoxSurvival)
library(survival)
library(dplyr)
library(survey)
library(ggplot2)
library(vaccine)
library(wCorr)
library(Hmisc)
source('CVE_functions.R')
```
# Data preprocessing

```{r data wrangling, echo=FALSE}
dt = read.csv('./COVID_realdata_ics_bama_nab_bcp20241210_processed_with_riskscore.csv')

# PBMC correlates analysis is restricted to PLWH
dt_PBMC_PP = dt %>% 
  filter(ph1.m1.ics == 1) %>%
  mutate(hybrid = (AGRP2N == 2.1) + 0) %>%
  mutate(is.subcohort = ifelse(ph2.m1.ics == 1 & IMMFL == 'Y', 1, 0))

# Define a stratification variable W corresponding to
# 4 baseline strata + case
# Mutate ph2 to logical 
dt_PBMC_PP = dt_PBMC_PP %>%
  mutate(W = ifelse(EventIndPrimary1 == 1, 1, 
                    ifelse(AGRP2N == 1, 2, 3))) %>%
  mutate(ph2.m1.ics_logical = ifelse(ph2.m1.ics == 1, TRUE, FALSE))

dt_PBMC_PP = dt_PBMC_PP %>%
  mutate(TBFL = ifelse(TBFL == '', 'N', TBFL),
         TBFL = ifelse(TBFL == 'Y', 1, 0)) %>%
  mutate(AGEGR1 = ifelse(AGEGR1 == '>40', 1, 0),
         BMIB2GR1 = ifelse(BMIB2GR1 == '>25', 1, 0),
         CD4B2GR1 = ifelse(is.na(CD4B2GR1), 'NotKnown', 
                           ifelse(CD4B2GR1 == '<=500', 'low', 'high')),
         riskscore = ifelse(is.na(riskscore), median(riskscore, na.rm = T), riskscore),
         enrollmentPeriodEarly = ifelse(CalendarDateEnrollment <= 90, 1, 0),
         enrollmentPeriodMid = ifelse((CalendarDateEnrollment > 90 & CalendarDateEnrollment <= 180), 1, 0),
         regionRSA = ifelse(REGION == 'South Africa', 1, 0))
```


## Define markers

```{r setmarkerofinterest, echo=TRUE}
# A11 = Spike BA.4/5; A02 = BA.4/5 N; A10 = Any BA.4/5
# C03: 'IFNg OR IL-2'; C04: 'IFNg OR IL-2 OR CD154'
T_vec = c('T4')
T_names_vec = c('CD4+')
C_vec = c('C03', 'C04')
C_names_vec = c('IFNg OR IL-2', 'IFNg OR IL-2 OR CD154')
A_vec = c('A02',  'A11')
A_names_vec = c('N BA.4/5',  'Spike BA.5')


antigen_vec = NULL
antigen_names_vec = NULL
for (i in 1:length(T_vec)) {
  for (j in 1:length(C_vec)) {
    for (k in 1:length(A_vec)) {
      antigen_vec = c(antigen_vec,
                      paste0(T_vec[i], C_vec[j], A_vec[k]))
      antigen_names_vec = c(antigen_names_vec,
                            paste0(T_names_vec[i], ' ', C_names_vec[j], '\n', A_names_vec[k]))
    }
  }
} 

mk_vec_b = paste0('B', antigen_vec)
names_vec_b = paste0('M0 ', antigen_names_vec, ' (%)')

mk_vec_p = paste0('M1', antigen_vec)
names_vec_p = paste0('Peak ', antigen_names_vec, ' (%)')

process <- function(x) log10(ifelse(x < 0.01, 0.01, x))

dt_PBMC_PP = dt_PBMC_PP %>%
  mutate_at(mk_vec_b, process) %>%
  mutate_at(mk_vec_p, process)

# Add fold-rise markers
for (antigen in antigen_vec) {
  dt_PBMC_PP = dt_PBMC_PP %>%
    mutate(!!paste0('fr', antigen) :=  !!sym(paste0('M1', antigen)) - !!sym(paste0('B', antigen)))
}

mk_vec_fr = paste0('fr', antigen_vec)
names_vec_fr = paste0('Fold-rise ', antigen_names_vec)
```


## Define adjusted covariates
```{r adj covs, echo=TRUE}
adj_vars = c('riskscore') 
n_var = 1
```

# Hybrid immunity group controlled risk analysis

```{r cohort HIPP, echo=TRUE}
dt_PBMC_PP_HIPP = dt_PBMC_PP %>%
  filter(hybrid == 1)
```

## Plot the controlled risk for baseline and Peak markers

```{r controlled VE HIPP, echo=FALSE, message=FALSE, warning=FALSE}
controlled_ve_mk_vec = c(mk_vec_b, mk_vec_p)
controlled_ve_names_vec = c(names_vec_b, names_vec_p)

for (i in 1:length(controlled_ve_mk_vec)){
  mk = controlled_ve_mk_vec[i]
  cat(mk, '\n')
  dat <- load_data(
  time = 'EventTimePrimary',
  event = 'EventIndPrimary1',
  vacc = 'hybrid',
  marker = mk,
  covariates = adj_vars,
  weights = "wt.m1.ics",
  ph2 = "ph2.m1.ics",
  data = dt_PBMC_PP)
  
b = vaccine::est_overall(dat, t_0 = 165, ve = FALSE)

overall_incidence = b$est[b$group == 'vaccine']  

ests_cox <- est_ce(dat = dat, type="Cox", t_0 = 165)
ests_np <- est_ce(dat = dat, type="NP", t_0 = 165)

df_np = data.frame(marker_level =  ests_np$cr$s,
                      controlled_risk =  ests_np$cr$est, 
                      ci_lower =  ests_np$cr$ci_lower, 
                      ci_upper =  ests_np$cr$ci_upper) 
write.csv(df_np, paste0( './source_data/Fig4_HIPP_',  mk, '.csv'))

mk_dist = dt_PBMC_PP_HIPP %>%
  filter(ph2.m1.ics == 1) %>%
  select(!!sym(mk), wt.m1.ics)

p = plot_cr2(ests_cox, ests_np, mk_dist, overall_incidence,
                     xlab_name = controlled_ve_names_vec[i],
                     title_name = 'Marker-Specific Risk',
                     t0 = 165, x_range = c(-2.2, 0.7),
                     x_breaks = log10(c(0.01, 0.03, 0.1, 0.3, 1, 3)),
        x_labels = c('0.01%', '0.03%', '0.1%', '0.3%', '1%', '3%'))

p = p + geom_line(linewidth = 1.1) + 
  geom_ribbon(ggplot2::aes(ymin = ci_lower, ymax = ci_upper), 
              alpha = 0.2, linewidth = 1.1, linetype = "dotted") +
  theme_bw(base_size = 30) + 
  theme(legend.position = 'none') + ggtitle('')

saveRDS(p, paste0('./raw_data_for_figure/', controlled_ve_mk_vec[i], '_HIPP.RData'))

ggsave(paste0('./Figure/', controlled_ve_mk_vec[i], '_HIPP.pdf'),
       p, width = 12, height = 8, units = 'in')
}
```


