---
title: "Coxph Report nAb"
author: "CoVPN 3008"
date: "2024-10-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preparing the dataset

```{r load pckages, echo=FALSE, warning=FALSE, message=FALSE}
library(CaseCohortCoxSurvival)
library(survival)
library(dplyr)
library(survey)
library(ggplot2)
library(GGally)
library(vaccine)
library(wCorr)
library(haven)
library(Hmisc)
library(coxphw)
library(weights)
```

```{r data wrangling, echo=FALSE}
dt = read.csv('./COVID_realdata_ics_bama_nab_bcp20241210_processed_with_riskscore.csv')
dt_adsl = read_sas('./adsl.sas7bdat')
dt_adsl = dt_adsl %>%
  select(USUBJID, AGEGR1, SEX, BMIB2GR1, CD4B2GR1, HIVDETBL2, REGION)
dt = merge(dt, dt_adsl, by.x = 'Subjectid', by.y = 'USUBJID')

dt_serum_PP = dt %>%
  filter(ph1.m1.sera == 1) %>%
  mutate(hybrid = AGRP2N %in% c(2.1, 4.1) + 0) %>%
  mutate(is.subcohort = ifelse(IMMFL == 'Y', 1, 0)) %>%
  mutate(log10M1BA45ID50 = log10(M1BA45ID50),
         log10BBA45ID50 = log10(BBA45ID50),
         frBA45ID50 = log10M1BA45ID50 - log10BBA45ID50,
         log10M1IGGSpikeIndex = log10(M1IGGMSDA16AU), #A16 = IgG S Index
         log10BIGGSpikeIndex = log10(BIGGMSDA16AU), 
         frIGGSpikeIndex = log10M1IGGSpikeIndex - log10BIGGSpikeIndex,
         log10M1IGGSpikeBA45 = log10(M1IGGMSDA23AU), # A23 = IgG S BA.4/5
         log10BIGGSpikeBA45 = log10(BIGGMSDA23AU), 
         frIGGSpikeBA45 = log10M1IGGSpikeBA45 - log10BIGGSpikeBA45,
         log10M1IGGN = log10(M1IGGMSDA15AU),
         log10BIGGN = log10(BIGGMSDA15AU))

# Define a stratification variable W corresponding to
# 4 baseline strata + case
# Mutate ph2 to logical 
dt_serum_PP = dt_serum_PP %>%
  mutate(W = ifelse(EventIndPrimary1 == 1, 1, 
                    ifelse(AGRP2N == 1, 2, 
                           ifelse(AGRP2N == 2.1, 3,
                                  ifelse(AGRP2N == 3, 4, 5))))) %>%
  mutate(ph2.m1.sera_logical = ifelse(ph2.m1.sera == 1, TRUE, FALSE))

dt_serum_PP = dt_serum_PP %>%
  mutate(TBFL = ifelse(TBFL == '', 'N', TBFL),
         TBFL = ifelse(TBFL == 'Y', 1, 0)) %>%
  mutate(AGEGR1 = ifelse(AGEGR1 == '>40', 1, 0),
         BMIB2GR1 = ifelse(BMIB2GR1 == '>25', 1, 0),
         CD4B2GR1 = ifelse(is.na(CD4B2GR1), 'NotKnown', 
                           ifelse(CD4B2GR1 == '<=500', 'low', 'high')),
         riskscore = ifelse(is.na(riskscore), median(riskscore, na.rm = T), riskscore),
         enrollmentPeriodEarly = ifelse(CalendarDateEnrollment <= 90, 1, 0),
         enrollmentPeriodMid = ifelse((CalendarDateEnrollment > 90 & CalendarDateEnrollment <= 180), 1, 0),
         regionRSA = ifelse(REGION == 'South Africa', 1, 0))

dt_serum_PP = dt_serum_PP %>%
  filter(AGRP2N == 1 | AGRP2N == 2.1)
```

## Define serum markers

```{r setmarkerofinterest, echo=TRUE}
serum_antigen_vec = c('BA45ID50', 'IGGSpikeBA45', 'IGGN')
serum_antigen_names_vec = c('nAb ID50 BA.4/5',  
                      'IgG Spike BA.5', 'IgG N Index')
serum_mk_vec_b = paste0('log10B', serum_antigen_vec)
serum_names_vec_b = c('M0 nAb-ID50 BA.4/5 (AU/ml)',
              'M0 IgG Spike BA.4/5 (AU/ml)',
              'M0 IgG N Index (AU/ml)')

serum_mk_vec_p = paste0('log10M1', serum_antigen_vec)
serum_names_vec_p = c('Peak nAb-ID50 BA.4/5 (AU/ml)',
              'Peak IgG Spike BA.4/5 (AU/ml)',
              'Peak IgG N Index (AU/ml)')


# A11 = Spike BA.4/5; A02 = BA.4/5 N; A10 = Any BA.4/5
# C03: 'IFNg OR IL-2'; C04: 'IFNg OR IL-2 OR CD154'
T_vec = c('T4')
T_names_vec = c('CD4+')
A_vec = c('A02', 'A11')
A_names_vec = c('N BA.4-5', 'Spike BA.5')
C_vec = c('C03', 'C04')
C_names_vec = c('IFNg OR IL-2', 'IFNg OR IL-2 OR CD154')

antigen_vec = NULL
antigen_names_vec = NULL
for (i in 1:length(T_vec)) {
  for (j in 1:length(A_vec)) {
    for (k in 1:length(C_vec)) {
      antigen_vec = c(antigen_vec,
                      paste0(T_vec[i], C_vec[k], A_vec[j]))
      antigen_names_vec = c(antigen_names_vec,
                            paste0(T_names_vec[i], ' ', C_names_vec[k], '\n', A_names_vec[j], ' Peptides'))
    }
  }
} 

ics_mk_vec_b = paste0('B', antigen_vec)
ics_names_vec_b = paste0('% M0 ', antigen_names_vec)

ics_mk_vec_p = paste0('M1', antigen_vec)
ics_names_vec_p = paste0('% Peak ', antigen_names_vec, ' (%)')


mk_vec_b = c(serum_mk_vec_b, ics_mk_vec_b)
names_vec_b = c(serum_names_vec_b, ics_names_vec_b)

mk_vec_p = c(serum_mk_vec_p, ics_mk_vec_p)
names_vec_p = c(serum_names_vec_p, ics_names_vec_p)


```


# Plot FS and PFS Spike BA.4/5

```{r process cluster data}
dt_ph2_AG21 = dt_serum_PP %>%
  filter(ph2.m1.ics == 1) %>%
  filter(hybrid == 1)

dt_FS = read.csv('./dt_COMPASS_Spike BA4-5.csv')

dt_M1 = dt_FS %>%
  mutate(PTID = paste0('C3008-', PTID),
         VISITNO = ifelse(VISITNO == 2, 'B', 'M1')) %>%
  dplyr::rename(Subjectid = PTID) %>%
  filter(VISITNO == 'M1') %>%
  mutate(M1_FS_final = FS_final,
         M1_PFS_final = PFS_final) %>%
  dplyr::select(Subjectid, M1_FS_final, M1_PFS_final)

dt_ph2_AG21_plot = merge(dt_ph2_AG21, dt_M1, by = 'Subjectid')  

p = ggplot(dt_ph2_AG21_plot, 
           aes(x = log10BBA45ID50, 
                  y = M1_FS_final)) +
  geom_point(aes(color = as.factor(EventIndPrimary1),
                 shape = as.factor(EventIndPrimary1),
                 size = as.factor(EventIndPrimary1))) +
  geom_hline(yintercept = median(dt_ph2_AG21_plot$M1_FS_final, na.rm = TRUE),
             color = 'black', alpha = 0.3, linetype = 'dashed', linewidth = 1.5) +
  geom_vline(xintercept = median(dt_ph2_AG21_plot$log10BBA45ID50, na.rm = TRUE),
             color = 'black', alpha = 0.3, linetype = 'dashed', linewidth = 1.5) +
  scale_color_manual('', values = c("steelblue", "#E69F00"), 
                        labels = c('COVID-19 Non-Case',
                                       'COVID-19 Case')) +
  scale_shape_manual('', values = c(16, 17), 
                     labels = c('COVID-19 Non-Case',
                                'COVID-19 Case')) +
  scale_size_manual('', values = c(4, 5.5), 
                    labels = c('COVID-19 Non-Case',
                               'COVID-19 Case')) +
  scale_x_continuous('M0 nAb-ID50 BA.4/5', 
                     limits = c(0, 5),
                     breaks = c(0, 1, 2,3,4,5)) +
  scale_y_continuous(expression(paste('Peak CD4+ Functionality Score Spike BA.4/5')),
                     limits = c(0.02, 0.07),
                     breaks = seq(0.02, 0.07, 0.01),
                     labels = c('0.02', '0.03', '0.04', '0.05', '0.06', '0.07')) +
  theme_bw(base_size = 28) +
  theme(legend.position = 'bottom')

ggsave('./Figure/two_marker_case_non_case_NN.pdf', p, width = 12, height = 12, units = 'in')
```


```{r add marginal}
library(ggExtra)
p2 = ggMarginal(p, type = 'density', groupColour = TRUE, groupFill = TRUE)
ggsave('./Figure/two_marker_case_non_case_NN_with_marginal.pdf', p2, width = 12, height = 12, units = 'in')

```

```{r}
dt_PP = dt_ph2_AG21_plot
res1 = NULL
res2 = NULL
res3 = NULL
mse1 = NULL
mse2 = NULL
for (i in 1:100){
n = dim(dt_ph2_AG21_plot)[1]
training_set_ind = sample(n, floor(0.6*n), replace = FALSE)
test_set_ind = setdiff(1:n, training_set_ind)


m3 = glm(EventIndPrimary1 ~ log10BBA45ID50 + riskscore, 
         data = dt_PP[training_set_ind,], family = 'binomial')

#m3 = glm(EventIndPrimary1 ~ riskscore, 
#         data = dt_PP[training_set_ind,], family = 'binomial')


m4 = glm(EventIndPrimary1 ~ log10BBA45ID50 + M1_FS_final + riskscore, 
         data = dt_PP[training_set_ind,], family = 'binomial')

#m5 = glm(COVIDIndD22toD181 ~ Day15pseudoneutid50_BA.4.BA.5 + Bcd4_IFNg.IL2_BA.4.5.S + risk_score, 
#         data = dt_PP[training_set_ind,], family = 'binomial')


a = data.frame(true_lable = dt_PP[test_set_ind,]$EventIndPrimary1, 
               #nAb = dt_PP[test_set_ind,]$Day15pseudoneutid50_BA.4.BA.5, 
               #T_cell = dt_PP[test_set_ind,]$Bcd4_IFNg.IL2_BA.4.5.S,  
               nAb_alone = predict(m3, dt_PP[test_set_ind,], type = 'response'), 
               nAb_T = predict(m4, dt_PP[test_set_ind,], type = 'response'))

prediction3 <- predict(m3, dt_PP[test_set_ind,], type="response")
r3 = roc(dt_PP[test_set_ind,]$EventIndPrimary1, prediction3)

prediction4 <- predict(m4, dt_PP[test_set_ind,], type="response")
r4 = roc(dt_PP[test_set_ind,]$EventIndPrimary1, prediction4)

#prediction5 <- predict(m5, dt_PP[test_set_ind,], type="response")
#r5 = roc(dt_PP[test_set_ind,]$COVIDIndD22toD91, prediction5)

mse1 = c(mse1, mean(sqrt((a$nAb_T - a$true_lable)^2)))
mse2 = c(mse2, mean(sqrt((a$nAb_alone - a$true_lable)^2)))
res1 = c(res1, auc(r3))
res2 = c(res2, auc(r4))
}
```
